// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcNUOjrOVwUKvhw8DehOI2dHyx-rfNUEU',
    appId: '1:759503671026:web:9280d2bf255c85e4298a6b',
    messagingSenderId: '759503671026',
    projectId: 'mynotes-app-68efb',
    authDomain: 'mynotes-app-68efb.firebaseapp.com',
    storageBucket: 'mynotes-app-68efb.appspot.com',
    measurementId: 'G-JQDS230TXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfD-4TE-Zf51uTqtVLs5laSfwoeHylRA',
    appId: '1:759503671026:android:5db301b92ae43612298a6b',
    messagingSenderId: '759503671026',
    projectId: 'mynotes-app-68efb',
    storageBucket: 'mynotes-app-68efb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYS3Iq9MFW2NOOtAP3xdZiONOmF_B4euc',
    appId: '1:759503671026:ios:418c3caf3326a140298a6b',
    messagingSenderId: '759503671026',
    projectId: 'mynotes-app-68efb',
    storageBucket: 'mynotes-app-68efb.appspot.com',
    iosClientId: '759503671026-1d0dvdno1pc4agn72lgu0p7rplgci0tq.apps.googleusercontent.com',
    iosBundleId: 'mynotes-app-68e',
  );
}
